### ISSUE TITLE
In some Mac environment, jdk4py cannot install java runtime.

### ISSUE THREAD

**Issue by MasaoMori** [atoti/jdk4py#53]
Hi,

I tried to install atoti-jupyterlab in Mac.

The case of homebrew -> pip is successful. But in the case of Conda and Docker, java runtime cannot be found. 

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/morimasao/miniconda3/lib/python3.9/site-packages/jdk4py/java-runtime/bin/java'

Are there anything necessary to do before installing atoti and jdk4py?

**Comment by tibdex** [comment]
Hi,

Can you please share more details:
- jdk4py version
- Conda version
- your architecture (Intel or Apple Silicon)

?

**Comment by MasaoMori** [comment]
Thank you for reply and sorry for the lack of information.

- jdk4py 11.0.7.3  
- conda 4.12.0 (Miniforge3  4.12.0-0)
- Apple Silicon

> FileNotFoundError: [Errno 2] No such file or directory: '/Users/morimasao/miniforge3/lib/python3.9/site-packages/jdk4py/java-runtime/bin/java'

Actually, ls result of the above directory site-package/jdk4py:

> __init__.py		java_version.txt
> __pycache__		lib_version.txt
>

**Comment by MasaoMori** [comment]
In the environment which jdk4py works normally, the directory have 

<pre>
__init__.py		java-runtime/		py.typed
__pycache__/		java_version.txt
</pre>

The directory java-runtime includes exec files.

**Comment by MasaoMori** [comment]
I I followed your advice and set it up. It worked well.

Thank you.
